#!/bin/bash

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  c_reset='\e[0m'
  c_yellow='\e[0;33m'
  c_purple='\e[0;35m'
fi

if [ -n "${BACKEND}" ]; then
  sed -i "s#{{BACKEND}}#${BACKEND}#" /etc/nginx/sites-available/*
else
  echo -e "$c_yellow[Warning]$c_reset Environment variable not set: $c_purple\$BACKEND$c_reset. Nginx will likely fail to start."
fi

if [ "${HSTS}" = "false" ]; then
  sed -e '/.*Strict-Transport-Security/ s/^#*/#/' -i /etc/nginx/sites-available/*
fi

exec "$@"
